config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "chat_rooms#index"

  resources :chat_rooms, only: [:index, :show, :new, :create, :destroy] do
    member do
      get 'join'
    end
    resources :posts, only: [:create]
  end

  resources :posts, only: [] do
    resources :thread_msgs, only: [:create]
  end

  resources :direct_messages, only: [:index, :create]
  resources :notifications, only: [:index]

  resources :users, only: [:show, :edit, :update] do
    member do
      get 'profile', to: 'users#show', as: :profile
      get 'edit', to: 'users#edit', as: :edit_profile
      patch 'update', to: 'users#update'
    end
  end
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :posts, dependent: :destroy
  has_one_attached :image

  validates :password, presence: true, if: :password_required?

  private

  def password_required?
    password.present?
  end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_chat_room, only: [:show, :join, :destroy]
  before_action :authorize_creator, only: [:destroy]

  def index
    @chat_rooms = if params[:search].present?
                    ChatRoom.where("name LIKE ?", "%#{params[:search]}%")
                  else
                    ChatRoom.all
                  end
  end

  def show
    @post = Post.new
    @chat_rooms = accessible_chat_rooms

    respond_to do |format|
      format.html # Pour la navigation classique
      format.js   # Pour les requêtes AJAX
    end
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    @chat_room = ChatRoom.new(chat_room_params)
    @chat_room.creator = current_user

    if @chat_room.save
      redirect_to chat_room_path(@chat_room), notice: "Le salon de discussion a été créé avec succès."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def join
    @post = Post.new
    @chat_rooms = accessible_chat_rooms

    if @chat_room.password.present?
      if session[:chat_room_ids]&.include?(@chat_room.id) || params[:password] == @chat_room.password
        session[:chat_room_ids] ||= []
        session[:chat_room_ids] << @chat_room.id unless session[:chat_room_ids].include?(@chat_room.id)
        redirect_to chat_room_path(@chat_room), notice: "Vous avez rejoint la salle."
      else
        flash[:alert] = "Mot de passe incorrect."
        render :show, status: :unauthorized
      end
    else
      redirect_to chat_room_path(@chat_room), notice: "Vous avez rejoint la salle."
    end
  end

  def destroy
    if @chat_room.destroy
      respond_to do |format|
        format.html { redirect_to chat_rooms_path, notice: "La salle a été supprimée avec succès." }
        format.js   # Pour les requêtes AJAX
      end
    else
      redirect_to chat_room_path(@chat_room), alert: "Impossible de supprimer la salle."
    end
  end

  private

  def set_chat_room
    @chat_room = ChatRoom.find(params[:id])
  end

  def chat_room_params
    params.require(:chat_room).permit(:name, :description, :password, :image)
  end

  def authorize_creator
    unless @chat_room.creator == current_user
      redirect_to chat_rooms_path, alert: "Vous n'avez pas l'autorisation de supprimer cette salle."
    end
  end

  def accessible_chat_rooms
    if session[:chat_room_ids].present?
      ChatRoom.where('password IS NULL OR id IN (?)', session[:chat_room_ids])
    else
      ChatRoom.where(password: nil)
    end
  end
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/views/chat_rooms/enter_password_form.html.erb
<h2 class="text-2xl font-bold text-white">Entrer le mot de passe pour accéder à la salle <%= @chat_room.name %></h2>

<%= form_with url: join_chat_room_path(@chat_room), method: :post, class: "space-y-4" do %>
  <div>
    <%= label_tag :password, "Mot de passe", class: "block text-white mb-2" %>
    <%= password_field_tag :password, nil, class: "w-full px-4 py-2 bg-gray-800 text-white rounded-lg border border-gray-700 focus:border-blue-500 focus:ring focus:ring-blue-500 focus:outline-none" %>
  </div>

  <div>
    <%= submit_tag "Entrer", class: "w-full bg-blue-600 hover:bg-blue-500 text-white font-bold py-2 px-4 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" %>
  </div>
<% end %>

app/views/chat_rooms/index.html.erb
<div class="flex h-screen overflow-hidden">
  <!-- Barre latérale -->
  <aside class="w-1/6 bg-gray-900 text-white flex flex-col items-center p-4">
    <ul class="w-full">
      <li class="w-full mb-4">
        <a href="<%= root_path %>" class="block text-lg py-2 px-4 bg-gray-800 rounded-lg hover:bg-gray-700 text-center">
          Accueil
        </a>
      </li>
    </ul>
  </aside>

  <!-- Contenu principal avec overflow-y-auto pour permettre le défilement vertical -->
  <main class="w-5/6 bg-gray-800 p-8 overflow-y-auto">
    <div class="flex justify-between items-center mb-6">
      <h2 class="text-2xl font-bold text-white">Threads</h2>
      <%= form_with url: chat_rooms_path, method: :get, class: "flex space-x-2" do %>
        <input type="text" name="search" class="input-text bg-gray-700 text-white px-4 py-2 rounded-lg" placeholder="Rechercher une salle" />
        <%= submit_tag "Rechercher", class: "bg-blue-600 hover:bg-blue-500 text-white px-4 py-2 rounded-lg" %>
      <% end %>
    </div>

    <!-- Grille des salles de discussion -->
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
      <% @chat_rooms.each do |chat_room| %>
        <div class="card bg-gray-700 rounded-lg shadow-md p-4 text-white">
          <% if chat_room.image.attached? %>
            <%= image_tag chat_room.image, class: "w-full h-32 object-cover rounded-lg mb-4" %>
          <% else %>
            <div class="w-full h-32 bg-gray-600 rounded-lg mb-4"></div>
          <% end %>

          <h3 class="text-lg font-bold"><%= chat_room.name %></h3>
          <p class="text-sm text-gray-300"><%= truncate(chat_room.description, length: 100) %></p>

          <div class="mt-4">
            <% if chat_room.password.present? %>
              <%= link_to "Rejoindre (protégé)", join_chat_room_path(chat_room), method: :post, class: "block w-full text-center bg-yellow-500 hover:bg-yellow-400 text-white py-2 rounded-lg" %>
            <% else %>
              <%= link_to "Rejoindre", join_chat_room_path(chat_room), method: :post, class: "block w-full text-center bg-blue-600 hover:bg-blue-500 text-white py-2 rounded-lg" %>
            <% end %>
          </div>

          <!-- Supprimer la room si c'est le créateur -->
          <% if chat_room.creator == current_user %>
            <div class="mt-4">
              <%= button_to "Supprimer", chat_room_path(chat_room), method: :delete, class: "block w-full text-center bg-red-600 hover:bg-red-500 text-white py-2 rounded-lg", data: { confirm: "Êtes-vous sûr de vouloir supprimer cette salle ?" } %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>

    <!-- Bouton de création de nouvelle salle -->
    <div class="mt-8 flex justify-center">
      <%= link_to "Créer une nouvelle salle", new_chat_room_path, class: "bg-grey-900 hover:bg-blue-500 text-white px-4 py-2 rounded-lg" %>
    </div>
  </main>
</div>

app/views/chat_rooms/new.html.erb
<h2>Créer une nouvelle salle de discussion</h2>

<%= form_with model: @chat_room, local: true, class: "space-y-4 w-1/2 h-1/2 bg-gray-900 bg-opacity-100 text-white flex flex-col items-center p-4 rounded-lg" do |f| %>
  <div>
    <%= f.label :name, "Nom de la salle" %>
    <%= f.text_field :name, class: "input-text", placeholder: "Nom de la salle" %>
  </div>

  <div>
    <%= f.label :description, "Description" %>
    <%= f.text_area :description, class: "input-text", placeholder: "Description de la salle" %>
  </div>

  <div>
    <%= f.label :image, "Image de la salle (optionnel)" %>
    <%= f.file_field :image, class: "input-file" %>
  </div>

  <div>
    <%= f.label :password, "Mot de passe (optionnel)" %>
    <%= f.password_field :password, class: "input-text", placeholder: "Mot de passe pour rejoindre" %>
  </div>

  <%= f.submit "Créer la salle", class: "btn-primary" %>
<% end %>

app/views/chat_rooms/show.html.erb
<div class="flex h-screen">
  <!-- Barre latérale avec min-width -->
  <aside class="min-w-[25rem] w-1/6 bg-gray-900 rounded-lg bg-opacity-100 text-white flex flex-col items-center p-4 overflow-y-auto">
    <div class="flex flex-col items-center mb-6">
      <% if current_user.avatar.attached? %>
        <%= image_tag current_user.avatar.variant(resize_to_fill: [100, 100]).processed, class: "w-20 h-20 rounded-full mb-2" %>
      <% else %>
        <%= image_tag 'gif.png', class: "w-20 h-20 rounded-full mb-2" %>
      <% end %>

      <h3 class="text-lg font-bold">
        <%= current_user.username.present? ? current_user.username : current_user.email %>
      </h3>

      <!-- Lien vers le profil de l'utilisateur -->
      <%= link_to 'Profil', edit_profile_user_path(current_user), class: "bg-grey-900 hover:bg-grey-300 text-white rounded-lg " %>

      <!-- Lien vers toutes les rooms -->
      <%= link_to 'Threads', chat_rooms_path, class: "bg-grey-900 hover:bg-grey-300 text-white rounded-lg" %>
    </div>

    <!-- Liste des chat rooms accessibles -->
    <ul class="w-full space-y-4">
      <% @chat_rooms.each do |chat_room| %>
        <% if chat_room.password.blank? || session[:chat_room_ids]&.include?(chat_room.id) %>
          <li class="w-full">
            <%= link_to chat_room.name, chat_room_path(chat_room), remote: true, class: "block text-lg py-2 px-4 bg-gray-800 bg-opacity-80 rounded-lg hover:bg-gray-700 text-center" %>
          </li>
        <% end %>
      <% end %>
    </ul>
  </aside>

  <!-- Contenu principal -->
  <main class="w-screen bg-gray-600 bg-opacity-80 p-8 rounded-lg">
    <div class="mb-4">
      <h2 class="text-2xl font-bold text-white"><%= @chat_room.name %></h2>
      <p class="text-white"><%= @chat_room.description %></p>
    </div>

    <!-- Section de messages -->
    <div class="bg-gray-700 bg-opacity-80 rounded-lg p-4 h-4/5 overflow-y-auto" id="chat-room-content">
      <% if @chat_room.posts.any? %>
        <% @chat_room.posts.each do |post| %>
          <div class="bg-gray-600 bg-opacity-80 rounded-lg p-4 mb-4">
            <div class="flex items-center mb-2">
              <% if post.user.avatar.attached? %>
                <%= image_tag post.user.avatar.variant(resize_to_fill: [40, 40]).processed, class: "w-10 h-10 rounded-full mr-4" %>
              <% else %>
                <%= image_tag 'gif.png', class: "w-10 h-10 rounded-full mr-4" %>
              <% end %>
              <h3 class="text-lg text-white">
                <%= post.user.username.present? ? post.user.username : post.user.email %>
              </h3>
            </div>
            <p class="text-white"><%= post.content %></p>

            <!-- Affichage de l'aperçu du lien -->
                  <% if post.preview_data.present? %>
          <div class="border border-gray-500 rounded-lg p-4 mt-2 bg-gray-800 max-w-full">
            <% if post.preview_data['video'].present? %>
              <!-- Conteneur responsif pour la vidéo -->
              <div class="relative w-full" style="padding-top: 56.25%;"> <!-- Pour un ratio 16:9 -->
                <iframe class="absolute top-0 left-0 w-full h-full" src="<%= post.preview_data['video'] %>" frameborder="0" allowfullscreen></iframe>
              </div>
            <% else %>
              <% if post.preview_data['image'].present? %>
                <%= image_tag post.preview_data['image'], class: 'w-full h-auto rounded-lg' %>
              <% end %>
              <h4 class="text-lg font-bold text-white mt-2"><%= post.preview_data['title'] %></h4>
              <p class="text-sm text-white break-words"><%= post.preview_data['description'] %></p>
            <% end %>
          </div>
        <% end %>

            <!-- Affichage du fichier envoyé -->
            <% if post.file.attached? %>
              <% if post.file.content_type.start_with?('image/') %>
                <%= image_tag post.file, class: "mt-2 w-48 h-auto rounded-lg" %>
              <% else %>
                <div class="mt-2">
                  <%= link_to post.file.filename.to_s, rails_blob_path(post.file, disposition: "attachment"), class: "text-blue-500 hover:underline" %>
                </div>
              <% end %>
            <% end %>
          </div>
        <% end %>
      <% else %>
        <p class="text-white">:/Il n'y a pas encore de messages dans cette salle.</p>
      <% end %>
    </div>

    <!-- Formulaire pour ajouter un message -->
    <div class="mt-4">
      <%= form_with(model: [@chat_room, @post], local: true, html: { multipart: true }, id: "message_form") do |form| %>
        <% if @post.errors.any? %>
          <div class="mb-4">
            <p class="text-red-500">Le message ne peut pas être vide.</p>
          </div>
        <% end %>

        <div class="flex space-x-2 items-center">
          <!-- Icône pour joindre un fichier -->
          <label for="file-upload" class="cursor-pointer bg-gray-600 bg-opacity-80 text-white p-2 rounded-lg hover:bg-gray-500">
            <svg class="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.172 7l-6.586 6.586a2 2 0 102.828 2.828l7.071-7.071a4 4 0 00-5.656-5.657l-8.486 8.486a6 6 0 008.485 8.485l7.071-7.071"></path>
            </svg>
          </label>
          <%= form.file_field :file, id: "file-upload", class: "hidden" %>

          <!-- Champ de texte pour le message -->
          <%= form.text_area :content, placeholder: "Entrez votre message", class: "w-full bg-gray-600 bg-opacity-80 text-white px-4 py-2 rounded-lg resize-none", rows: 1, id: "message_content" %>

          <!-- Flèche pour envoyer le message -->
          <button type="submit" class="bg-blue-600 hover:bg-blue-500 text-white p-2 rounded-lg flex items-center">
            <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
          </button>
        </div>
      <% end %>
    </div>
  </main>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    const messageForm = document.getElementById('message_form');
    const messageContent = document.getElementById('message_content');

    // Envoi du message avec la touche Entrée
    messageContent.addEventListener('keydown', function(event) {
      if (event.key === 'Enter' && !event.shiftKey) {
        event.preventDefault(); // Empêche le saut de ligne
        messageForm.submit(); // Soumet le formulaire
      }
    });
  });
</script>