config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "chat_rooms#index"

  resources :chat_rooms, only: [:index, :show, :new, :create, :destroy] do
    member do
      get 'join'
    end
    resources :posts, only: [:create]
  end

  resources :posts, only: [] do
    resources :thread_msgs, only: [:create]
  end

  resources :direct_messages, only: [:index, :create]
  resources :notifications, only: [:index]

  resources :users, only: [:show, :edit, :update] do
    member do
      get 'profile', to: 'users#show', as: :profile
      get 'edit', to: 'users#edit', as: :edit_profile
      patch 'update', to: 'users#update'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <title>STATION</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@^2.0/dist/tailwind.min.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
  </head>

  <body style="background-image: <%= current_user&.background&.attached? ? "url(#{url_for(current_user.background)})" : asset_path('gif.png') %>; background-size: cover; background-repeat: no-repeat;" class="min-h-screen">
    <!-- Header -->
    <header class="bg-gray-900 text-white p-5 shadow-md">
      <div class="container mx-auto flex justify-between">
        <%= link_to "STATION™", root_path, class: "text-xl font-bold" %>
        <% if user_signed_in? %>
          <div class="flex items-center space-x-4">
            <%= link_to current_user.username, profile_user_path(current_user), class: "text-white hover:text-gray-300" %>
            <%= button_to 'Log out', destroy_user_session_path, method: :delete, class: 'bg-red-600 px-4 py-2 rounded-lg hover:bg-red-500' %>
          </div>
        <% else %>
          <%= link_to "Se connecter", new_user_session_path, class: "text-white hover:text-gray-300" %>
          <%= link_to "S'inscrire", new_user_registration_path, class: "ml-4 text-white hover:text-gray-300" %>
        <% end %>
      </div>
    </header>

    <div class="container mx-auto mt-8">
      <%= yield %>
    </div>

  </body>
</html>